DROP TABLE IF EXISTS user_details;

CREATE TABLE IF NOT EXISTS user_details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_name TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE,
    full_name TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    is_active INTEGER NOT NULL DEFAULT 1,
    is_email_verified INTEGER NOT NULL DEFAULT 0,
    last_login_at DATETIME,
    last_login_ip TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
);

INSERT OR IGNORE INTO user_details (
    id,
    user_name,
    email,
    full_name,
    password_hash,
    role,
    is_active,
    is_email_verified,
    created_at
)
VALUES (
    1,
    'admin',
    'admin@example.com',
    'System Administrator',
    'root',
    'admin',
    1,
    0,
    CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_description_details (
    jd_id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name TEXT NOT NULL,
    file_saved_location TEXT NOT NULL,

    -- JD metadata
    title TEXT,                    -- job title/role

    -- AI/processing metadata
    parsed_summary TEXT,           -- short summary generated by your agent
    last_reviewed_at DATETIME,
    last_reviewed_by TEXT,

    -- resume counters
    resumes_uploaded_count INTEGER NOT NULL DEFAULT 0,
    processed_resumes_count INTEGER NOT NULL DEFAULT 0,

    -- status & audit
    status TEXT NOT NULL DEFAULT 'active',
    uploaded_by TEXT,
    is_active BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS resume_details (
    resume_id INTEGER PRIMARY KEY AUTOINCREMENT,
    jd_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    file_location TEXT NOT NULL,

    -- candidate info (extracted or entered)
    candidate_name TEXT,
    candidate_email TEXT,
    candidate_phone TEXT,

    -- AI/processing metadata
    parsed_summary TEXT,
    parsed_skills TEXT,
    match_score REAL,

    -- status & audit
    status TEXT NOT NULL DEFAULT 'new',
    uploaded_by TEXT,
    is_active BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME,

    FOREIGN KEY (jd_id) REFERENCES job_description_details (jd_id)
);

CREATE TABLE IF NOT EXISTS resume_analysis_details (
    analysis_id INTEGER PRIMARY KEY AUTOINCREMENT,
    resume_id INTEGER NOT NULL,
    jd_id INTEGER NOT NULL,

    -- Raw JSON result from LLM agent
    analysis_json TEXT NOT NULL,

    -- Optional extracted fields for quick querying
    match_score REAL,

    -- audit fields
    processed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_by TEXT,

    FOREIGN KEY (resume_id) REFERENCES resume_details (resume_id),
    FOREIGN KEY (jd_id) REFERENCES job_description_details (jd_id)
);
